### ISSUE TITLE
Search Result Are Limited To 5 Results

### ISSUE THREAD

**Issue by apddequina** [Blair2004/NexoPOS-4x#278]
While using the stock adjustment search field. The suggested results are always limited to 5, making it impossible to pick any other product. 

![image](https://user-images.githubusercontent.com/89784400/131339327-00afa64d-e992-4685-b5ad-4059fa4201ae.png)

**Comment by Blair2004** [comment]
fixed on a recent commit. Scheduled for 4.5

**Comment by apddequina** [comment]
Hello,

Will the update be pushed through tomorrow (Tuesday, September 7)? As per your last email as the current issue is really hindering us from our inventory management.

**Comment by apddequina** [comment]
Hello, 

It seems that whenever I search for a product in the stock adjustment module, it does not display the product that I try to search. Do you think the issue had gone worse?

https://prnt.sc/1rjyymj

**Comment by apddequina** [comment]
The issue is still not fixed.

As you can see I have 5 products encoded into the system...
https://prnt.sc/1rl1nwu

But when I try to search in the stock adjustment module, it does not appear.
https://prnt.sc/1rl1njl
